# Gravity of environment for dlo simulation
gravity_x: 0.0 # m/s^2
gravity_y: 0.0 # m/s^2
gravity_z: -9.81 # m/s^2

dt: 0.001 # seconds. Simulated time per iteration of the dlo simulation.
set_sim_rate_auto: false  # to set the simulation rate and dt automaticall, do not use
num_substeps: 30 # Number of substeps per iteration based on 2019 Small Steps XPBD paper.
num_steps: 1 # experimental only. do not change from 1

dlo_l: 2.25 # 3.3528 # dlo length in meters
dlo_r: 0.0035 # 0.0035 # dlo radius in meters
dlo_density: 1000.0 # dlo mass per meter cube (kg/m^3)
dlo_resolution: 10 # particle resolution per meter 

dlo_stretching_compliance: 1.0 # 1.0 # 0.01
dlo_shearing_compliance_x: 1.0 # 1.0 # 0.01
dlo_shearing_compliance_y: 1.0 # 1.0 # 0.01

dlo_twisting_compliance: 1.0 # 2.0 # 0.01
dlo_bending_compliance_x: 1.0 # 2.0 # 0.01 
dlo_bending_compliance_y: 1.0 # 2.0 # 0.01 

initial_height: 1.10 # initial dlo height from ground (m)

num_hang_corners: 1 # num of corners to hang dlo from (options: 0,1,2)

simulation_rate: 1000.0
rendering_rate: 60.0 # Hz, frequency to publish the dlo vertices and edges to RVIZ visualization markers

# wrench_pub_rate: 100.0 # Hz, frequency to publish the dlo forces at the attachment points

dlo_points_topic_name: "dlo_points" # topic name to publish the RVIZ visualization marker msgs
dlo_points_frame_id: "map" # the reference tf frame ID that the visualization marker msgs are published in.

# # Odometry topics that publishes robot positions to the dlo simulator
# odom_01_topic_name: "d1/ground_truth/fabric_mount/odom"
# odom_02_topic_name: "d2/ground_truth/fabric_mount/odom"
# odom_03_topic_name: "d3/ground_truth/fabric_mount/odom"
# odom_04_topic_name: "d4/ground_truth/fabric_mount/odom"

# # TF frame names that the dlo is assumed to be attached.
# wrench_01_frame_id: "d1_tf_fabric_mount_link"
# wrench_02_frame_id: "d2_tf_fabric_mount_link"
# wrench_03_frame_id: "d3_tf_fabric_mount_link"
# wrench_04_frame_id: "d4_tf_fabric_mount_link"

# dlo_rob_z_offset_: 0.0 # z offset between the specified frame and dlo attachement

# # Published topic names of the forces of attached robots.
# wrench_01_topic_name: "d1/dlo_wrench_stamped"
# wrench_02_topic_name: "d2/dlo_wrench_stamped"
# wrench_03_topic_name: "d3/dlo_wrench_stamped"
# wrench_04_topic_name: "d4/dlo_wrench_stamped"

