# How much we weigh theta vs x,y in choosing safe swarm velocity
# Higher theta_scale ==> Swarm velocity follows angle commands closer
# (But doesn't follow XY commands as closely)
theta_scale: 1.0 # (m/s)/(rad/s)



desired_swarm_vel_topic_name: /ui/desired_swarm_vel
just_swarm_frame_vel_input_topic_name: /ui/just_swarm_vel

frame_sync_topic_name: /ui/tf_changer
robot_enable_status_topic: /ui/robot_enable_status

footprint_publish_topic_name: "swarm_footprint"

# Robot footprints.
footprint_0: [[0.345, -0.260], [0.345, 0.260], [-0.345, 0.260], [-0.345, -0.260]]
vel_lim_x_0: 1.3
vel_lim_y_0: 1.3
vel_lim_theta_0: 4.0 
acc_lim_x_0: 1.0
acc_lim_y_0: 1.0
acc_lim_theta_0: 2.0  

footprint_1: [[0.345, -0.260], [0.345, 0.260], [-0.345, 0.260], [-0.345, -0.260]]
vel_lim_x_1: 1.3
vel_lim_y_1: 1.3
vel_lim_theta_1: 4.0 
acc_lim_x_1: 1.0
acc_lim_y_1: 1.0
acc_lim_theta_1: 2.0  

footprint_2: [[0.345, -0.260], [0.345, 0.260], [-0.345, 0.260], [-0.345, -0.260]]
vel_lim_x_2: 1.3
vel_lim_y_2: 1.3
vel_lim_theta_2: 4.0 
acc_lim_x_2: 1.0
acc_lim_y_2: 1.0
acc_lim_theta_2: 2.0  

footprint_3: [[0.345, -0.260], [0.345, 0.260], [-0.345, 0.260], [-0.345, -0.260]]
vel_lim_x_3: 1.3
vel_lim_y_3: 1.3
vel_lim_theta_3: 4.0 
acc_lim_x_3: 1.0
acc_lim_y_3: 1.0
acc_lim_theta_3: 2.0