antenna_offsets: # in m
  '0': 0.0 # d1_tag_1
  '1': 0.0 # d1_tag_2
  '2': 0.0 # d2_tag_1
  '3': 0.0 # d2_tag_2
  '4': 0.0 # d3_tag_1
  '5': 0.0 # d3_tag_2
  '6': 0.0 # d4_tag_1
  '7': 0.0 # d4_tag_2
  '100': 0.0 # anchor_1
  '101': 0.0 # anchor_2
  '102': 0.0 # anchor_3
  '103': 0.0 # anchor_4
  # '2A32': 0.065 # Mobile Anchor 1 LL # ON THE FINAL DEMO AREA